import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";
import ReduxProvider from "./ReduxProvider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutType = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutType) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        <ReduxProvider>
          <Nav />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
